---
title: "week9"
author: "Lyke Esselink"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
# remotes::install_github('jaburgoyne/compmus')
```


```{r setup, include=FALSE}
library(tidyverse)
library(compmus)
```

# breakout 2

```{r}
bzt <- read_csv("../dat/bzt-timbre.csv")
bzt_p <- read_csv("../dat/bzt-pitches.csv")
```

```{r}
bzt |>
  compmus_wrangle_timbre() |> 
  mutate(timbre = map(timbre, compmus_normalise, "manhattan")) |>
  compmus_gather_timbre() |>
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = mfcc,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  scale_fill_viridis_c() +                              
  theme_classic()
```

# Breakout 3

```{r}
bzt |>
  compmus_wrangle_timbre() |> 
  filter(row_number() %% 50L == 0L) |> 
  mutate(timbre = map(timbre, compmus_normalise, "euclidean")) |>
  compmus_self_similarity(timbre, "cosine") |> 
  ggplot(
    aes(
      x = xstart + xduration / 2,
      width = 50 * xduration,
      y = ystart + yduration / 2,
      height = 50 * yduration,
      fill = d
    )
  ) +
  geom_tile() +
  coord_fixed() +
  scale_fill_viridis_c(guide = "none") +
  theme_classic() +
  labs(x = "", y = "")
```

```{r}
bzt_p |>
  compmus_wrangle_chroma() |> 
  filter(row_number() %% 50L == 0L) |> 
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) |>
  compmus_self_similarity(pitches, "cosine") |> 
  ggplot(
    aes(
      x = xstart + xduration / 2,
      width = 50 * xduration,
      y = ystart + yduration / 2,
      height = 50 * yduration,
      fill = d
    )
  ) +
  geom_tile() +
  coord_fixed() +
  scale_fill_viridis_c(guide = "none") +
  theme_classic() +
  labs(x = "", y = "")
```

